# For the Next.js app
FROM node:18-alpine

WORKDIR /app/client

# Copy only the package.json and package-lock.json to leverage Docker layer caching
COPY package*.json ./

# Install production dependencies
RUN npm ci --only=production

# Copy the rest of the application code
COPY . .

# Expose the desired port (default is 3000 for Next.js)
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]
